# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [dollar, fail]
patreon: # Replace with a single Patreon username mouse36872
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username Toshiba 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username marshal
issuehunt: # Replace with a single IssueHunt username times
otechie: # Replace with a single Otechie username amvets 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Ibotta.com','https://Wikipedia.com','https://Verizon.com']
